### ISSUE TITLE
Publish greyscale image error

### ISSUE THREAD

**Issue by chanyoungjung** [prophesee-ai/prophesee_ros_wrapper#10]
When I launch the prophesee_publisher file, the greyscale image is not published even if I changed to like this (<param name="publish_graylevels" value="true" />)

I checked the publishGrayLevels function in source code and raise the try catch error. 

Please let me know if there are my mistakes.

**Comment by nlyubova** [comment]
Hello @chanyoungjung 
which camera generation do you have ?

**Comment by chanyoungjung** [comment]
I think it's third.

> Hello @chanyoungjung
> which camera generation do you have ?

**Comment by nlyubova** [comment]
Not all cameras has gray-levels data only some older versions.
Do you see gray-level data when you use prophesee_viewer (without any ROS)?

**Comment by Leedk3** [comment]
Here is the same issue.

I have tried to show the graylevel image on the ROS. 
However, It didn't work as showing this error code
                            Prophesee driver exception
                            Error 102101: Unsupported feature of the camera.

I think my camera model is PSEE300EVK.
Actually, I am not sure my model supports the graylevel image and that is why ros-publisher cannot show the image.

In detail, I think the problem occurs in this code. I attach the code below.
Lastly, when I checked the try-catch(exception handling), I realized that the code is not executed in the "try" but in the "catch".
---------------------------------------------------------------------------------------------------------------------------
void PropheseeWrapperPublisher::publishGrayLevels() {
    // Initialize and publish a gray-level frame
    try {
        camera_.set_exposure_frame_callback(graylevel_rate_, [this](Prophesee::timestamp t, const cv::Mat &f) {
            // Check the number of subscribers to the topic
            if (pub_gl_frame_.getNumSubscribers() <= 0)
                return;

            // Define the message for the gray level frame
            cv_bridge::CvImage gl_frame_msg;
            gl_frame_msg.header.stamp    = last_timestamp_;
            gl_frame_msg.header.frame_id = camera_name_;
            gl_frame_msg.encoding        = sensor_msgs::image_encodings::MONO8;
            gl_frame_msg.image           = tone_mapper_(f);

            // Publish the message
            pub_gl_frame_.publish(gl_frame_msg);

            ROS_DEBUG("Graylevel data are available");
        });
    } catch (Prophesee::CameraException &e) {
        if (e.code().value() & Prophesee::CameraErrorCode::UnsupportedFeature)
            publish_graylevels_ = false;
        else {
            ROS_WARN("%s", e.what());
            publish_graylevels_ = false;
        }
    }
}

**Comment by nlyubova** [comment]
hello @Leedk3,
PSEE300EVK doesn't have any gray-level events, as none of our current sensors. So, it's normal that you don't get these data in ROS
