### ISSUE TITLE
How to change biases

### ISSUE THREAD

**Issue by TimoStoff** [prophesee-ai/prophesee_ros_wrapper#16]
Is it possible to change camera biases for a Prophesee camera using the ROS driver? Currently I need to terminate my ROS program, launch the metavision player then restart ROS again to see the effects of the new biases.

**Comment by nlyubova** [comment]
Hello,
yes it is possible to change biases via a ".bias" file. This file can be provided in the launch file https://github.com/prophesee-ai/prophesee_ros_wrapper/blob/master/prophesee_ros_driver/launch/prophesee_publisher.launch
or you can provide it directly in the code of publisher. 
However, you cannot change the biases interactively. So, after each change, you need to restart the ROS node. However, once you find biases that suit you then you can save them all to the ".bias" file and use this file.
