### ISSUE TITLE
Converting rosbag to .raw format that is compatible with metavision

### ISSUE THREAD

**Issue by abhishek1411** [prophesee-ai/prophesee_ros_wrapper#18]
Hello,
I am working with a GEN3 event camera for recording data from a traffic scenario and multiple sensors to rosbag. I would like to convert the event-based camera information from the rostopic to .raw format which is compatible with metavision. Is there a way to do that?

**Comment by abhishek1411** [comment]
Hii,
Directly recording from a Metavision is not preferable as I would like to record data from a Frame-based camera and an Event-based camera simultaneously in a real-world traffic scenario and hence recording it through ROS is much more relevant. And also, Prohesee had released a large-scale dataset ( Learning to Detect Objects with a 1 Megapixel Event Camera) which I assume would be collected using ROS and then converted to relevant formats.

**Comment by nlyubova** [comment]
unfortunately, the functionality to convert data from rosbugs to RAW files doesn't exist for the moment.

The dataset was collected without using ROS, but internal Prophesee tools. The data format is compatible with Metavision SDK

**Comment by abhishek1411** [comment]
Oh okay, Thank you for the reply. Any suggestions on converting the rosbag information to a relevant format or in the future will that be addressed?

**Comment by nlyubova** [comment]
What about reading from a rosbag and processing data directly ?
Alternatively, you could read from a rosbag and write to a DAT file using this class metavision_core.event_io.DatWriter (https://docs.prophesee.ai/2.2.1/metavision_sdk/modules/core/python_api/event_io.html). Then DAT files can be processed in our samples.

For the moment, we don't plan to write a converter to RAW format. Maybe we could provide some conversion to DAT in future.
