### ISSUE TITLE
Couldn't able to find the Prophesee SDK

### ISSUE THREAD

**Issue by analogicalnexus** [prophesee-ai/prophesee_ros_wrapper#2]
For some reason, this command is not working?

sudo apt install prophesee-*

Could you please help me with this?

**Comment by nlyubova** [comment]
Hi,
we have sent you an invitation to our Knowledge Center. In the Knowledge Center, you should be able to download Prophesee SDK. Please, let us know if it works for you?

**Comment by dmigliore** [comment]
Hi @analogicalnexus
did you solve your issue?
