### ISSUE TITLE
 Frame rate gets slower and slower when run  prophesee_viewer.launch

### ISSUE THREAD

**Issue by XinchengYuYi** [prophesee-ai/prophesee_ros_wrapper#24]
My Prophesee Evaluation Kit Cameras is EVKV3 Gen4.1，when I run:
`roslaunch prophesee_ros_driver prophesee_viewer.launch`
the frame rate in the CD Event Window will get slower and slower,why?

**Comment by nlyubova** [comment]
Hello,
This ROS wrapper wasn't yet tested on EVK3, and it is not optimized for high event rate. Does this issue happen only with ROS wrapper or with Metavision software to ( like Metavision Studio, for example) ?

**Comment by XinchengYuYi** [comment]
> Hello, This ROS wrapper wasn't yet tested on EVK3, and it is not optimized for high event rate. Does this issue happen only with ROS wrapper or with Metavision software to ( like Metavision Studio, for example) ?
Yes, this phenomenon only happen with ROS wrapper, we test with Metavision Studio or Python SDK,  its display is normal.

**Comment by nlyubova** [comment]
This wrapper is not optimized for high data rate. 
To solve this issue, we suggest you to reduce the amount of data: either by using less sensitive biases, or ERC, or ROI.

**Comment by brdav** [comment]
Hi,
is the limited throughput only a concern for prophesee_viewer, or also when only recording to a rosbag with prophesee_publisher?

**Comment by nlyubova** [comment]
In both cases, we recommend you to reduce the number of events by tuning biases, applying filters, like Anti-Flicker, ERC, STC, Trail, etc. 

To be sure not to loose any data, the preferred way for data recording is using SDK directly (like Metavision Studio, Player, Viewer, etc)

**Comment by jiheddachraoui** [comment]
Hello @nlyubova , how can i add these parameters to the ros publisher. thank you

> In both cases, we recommend you to reduce the number of events by tuning biases, applying filters, like Anti-Flicker, ERC, STC, Trail, etc.
> 
> To be sure not to loose any data, the preferred way for data recording is using SDK directly (like Metavision Studio, Player, Viewer, etc)

**Comment by nlyubova** [comment]
This ROS driver is not optimized for high event rate. It should be seen as an example only.
Therefore, you need either to reduce the event rate (e.g. using sensor biases) to use this code or optimize the code for higher event rates.
We have just added a sensor biases file https://github.com/prophesee-ai/prophesee_ros_wrapper/blob/master/prophesee_ros_driver/cfg/imx636_CD_less_sensitive.bias with less sensitive settings generating less events from the sensor. This file is for one of our recent sensors (IMX636). If you use this sensor, then you can already use this file by setting the path to it in https://github.com/prophesee-ai/prophesee_ros_wrapper/blob/master/prophesee_ros_driver/launch/prophesee_publisher.launch#8 If you have a different sensor then you will need to tune the sensor biases on your own or contact our support for help explaining your application and the sensor used. 
We can also farther tune the settings and set the maximum event rate by adding ERC mentioned before. Indeed, it is not yet in the launch file. 

Alternatively, you could check https://github.com/ros-event-camera/metavision_driver for a more optimized data gathering with ROS
