### ISSUE TITLE
Camera Biases

### ISSUE THREAD

**Issue by mohammedsalah98** [prophesee-ai/prophesee_ros_wrapper#25]
Hi
Is it possible to change the biases of a specific model of prophesee cameras. I know the bias values that I use in the metavision software but how do I use the same ones in ROS.

**Comment by nlyubova** [comment]
Hi,
yes, you can use biases easily. You can use any "file.bias" with the publisher. You need to give the path to this file.bias in the launch file here https://github.com/prophesee-ai/prophesee_ros_wrapper/blob/master/prophesee_ros_driver/launch/prophesee_publisher.launch 

You can also set it directly in the code if you prefer.
