### ISSUE TITLE
Compling issues on Ubuntu 20.04 ROS Noetic 

### ISSUE THREAD

**Issue by adrienzhh** [prophesee-ai/prophesee_ros_wrapper#32]
It seems the current 5.0.0 version of the wrapper cannot be compiled due to some naming changes in both library and function from openeb library. 

It's not really clearly indicated in README, but for future reference, **openeb 4.6.2** and **ROS wrapper 3.0.0** are compatible and can compile successfully on my Ubuntu 20.04.

**Comment by nlyubova-psee** [comment]
Hello,
Indeed, the current 5.0.0 version requires Metavision SDK or [OpenEB](https://github.com/prophesee-ai/openeb) v5.0.0.
For the old version, we have just created a missing tag 4.6.2.
