### ISSUE TITLE
Unable to locate package prophesee-*

### ISSUE THREAD

**Issue by jackliang85** [prophesee-ai/prophesee_ros_wrapper#8]
Following the instructions in the prophesee knowledge center, I tried to install the prophesee driver sdk for Linux. My system is a Jetson Nano running Ubuntu 18.04 64 bit.
When I reached the step: 
$ sudo apt install prophesee-* metavision-*

I get errors:
E: Unable to locate package prophesee-*
E: Couldn't find any package by glob 'prophesee-*'
E: Couldn't find any package by regex 'prophesee-*'

Any advice?

**Comment by nlyubova** [comment]
hello,
thanks for your interest to our ROS wrapper!
Indeed, you cannot install this software without adding Prophesee server to your list of known repositories. 
As mentioned in the README, you would need to request an account to our Knowledge Center for instructions. For this, please, provide us a short description of your research project, company name and request an access to Knowledge Center via support@prophesee.ai.

Thanks,
Natalia

**Comment by jackliang85** [comment]
I have an account and access to the knowledge center and was following the instructions in there to install the linux driver sdk. I have added the prophesee server to the list of known repositories as per the instructions provided in there.

**Comment by nlyubova** [comment]
Good news. 
However, the installation procedure for Jetson Nano are slightly different from instructions on Knowledge Center.
Please, right us to support@prophesee.ai and we'll share SW by mail.

Regards,
Natalia
